"""
Script to create the manual-gen-images/prompts directory structure
and populate it with AI image generation prompts.
"""

import os
from pathlib import Path

# Define prompts
PROMPTS = {
    "p001": "Generate a photorealistic candid photo of an adult waiting at a city bus stop on a rainy evening, wet pavement reflections, natural lighting, 35mm lens, slight motion blur.",
    "p002": "Generate a candid photo of an adult walking down a sidewalk in the early morning, wearing casual clothes, soft sunlight, realistic skin texture, shallow depth of field.",
    "p003": "Generate a photo of an adult sitting alone at a café table, looking at their phone, indoor lighting, realistic shadows, documentary style.",
    "p004": "Generate a natural photo of two adults talking while walking through a park, trees in background, overcast lighting, casual candid moment.",
    "p005": "Generate a photo of an adult standing at a crosswalk waiting for the light to change, urban street setting, realistic reflections and shadows.",
    "p006": "Generate a candid photo of an adult sitting on a park bench reading a book, afternoon sunlight filtering through trees, realistic colors.",
    "p007": "Generate a photo of an adult grocery shopping in a supermarket aisle, shelves full of products, fluorescent lighting, slight motion blur.",
    "p008": "Generate a photo of an adult cooking in a small kitchen, vegetables on the counter, warm indoor lighting, natural clutter.",
    "p009": "Generate a candid photo of an adult tying their shoes while sitting on apartment building steps, midday light, realistic textures.",
    "p010": "Generate a photo of an adult waiting in line at a coffee shop, menu board in background, indoor lighting, candid framing.",
    "p011": "Generate a natural photo of an adult standing at a train platform, blurred train tracks in background, cool lighting.",
    "p012": "Generate a photo of an adult walking a dog on a residential street, late afternoon sun, realistic shadows.",
    "p013": "Generate a candid photo of an adult sitting at a desk working on a laptop, papers and notebooks scattered, soft window light.",
    "p014": "Generate a photo of an adult standing near a window inside an apartment, daylight coming in, natural posture.",
    "p015": "Generate a photo of an adult walking through a parking lot carrying grocery bags, cloudy sky, realistic color tones.",
    "p016": "Generate a candid photo of an adult sitting on public transit, holding onto a pole, fluorescent lighting, realistic noise.",
    "p017": "Generate a photo of an adult standing in a hallway of an apartment building, neutral walls, overhead lighting.",
    "p018": "Generate a photo of an adult leaning against a wall checking their phone, urban setting, shallow depth of field.",
    "p019": "Generate a natural photo of an adult standing in a doorway of a small shop, indoor lighting spilling outside.",
    "p020": "Generate a photo of an adult waiting at a pedestrian crossing at night, streetlights, slight grain.",
    "p021": "Generate a photo of an adult carrying a backpack walking down a quiet street, early evening light.",
    "p022": "Generate a candid photo of an adult sitting at a bus shelter, cloudy weather, realistic reflections on glass.",
    "p023": "Generate a photo of an adult entering a convenience store, automatic doors opening, indoor lighting visible.",
    "p024": "Generate a photo of an adult sitting at a dining table eating a meal, warm indoor lighting, realistic clutter.",
    "p025": "Generate a candid photo of an adult standing in line at a checkout counter, store interior, natural posture.",
    "p026": "Generate a photo of a messy bedroom desk with a laptop, notebooks, cables, and a coffee mug, daylight from window.",
    "p027": "Generate a photo of a small kitchen sink filled with dishes, sponge on the side, warm indoor lighting.",
    "p028": "Generate a photo of a living room with a couch, coffee table, and scattered magazines, natural daylight.",
    "p029": "Generate a photo of a hallway inside an apartment building, neutral walls, overhead lighting, realistic perspective.",
    "p030": "Generate a photo of a bathroom mirror with water spots, sink visible, soft indoor lighting.",
    "p031": "Generate a photo of a dining table with plates, cups, and leftovers, evening indoor lighting.",
    "p032": "Generate a photo of a home office with a desk, monitor, keyboard, and sticky notes, daylight through blinds.",
    "p033": "Generate a photo of a refrigerator interior with food containers and bottles, interior fridge light.",
    "p034": "Generate a photo of a cluttered entryway with shoes, jackets, and a doormat, natural lighting.",
    "p035": "Generate a photo of a bookshelf filled with books and small objects, indoor lighting, shallow depth of field.",
    "p036": "Generate a photo of a laptop on a café table, coffee cup beside it, blurred background.",
    "p037": "Generate a photo of a kitchen counter with groceries laid out, fruits and vegetables, indoor lighting.",
    "p038": "Generate a photo of a television on a stand in a living room, soft ambient lighting.",
    "p039": "Generate a photo of a bed with wrinkled sheets and pillows, morning light.",
    "p040": "Generate a photo of a washing machine in a laundry room, overhead lighting.",
    "p041": "Generate a photo of a dining chair pushed slightly away from a table, natural indoor shadows.",
    "p042": "Generate a photo of a window with light curtains blowing slightly, daylight.",
    "p043": "Generate a photo of a coffee maker on a kitchen counter, mug underneath, indoor lighting.",
    "p044": "Generate a photo of a microwave on a kitchen counter, digital clock visible.",
    "p045": "Generate a photo of a hallway closet with coats hanging inside, soft indoor lighting.",
    "p046": "Generate a photo of a desk drawer open with office supplies inside.",
    "p047": "Generate a photo of a sink faucet dripping water, close-up, realistic reflections.",
    "p048": "Generate a photo of a dining table set for one person, natural indoor lighting.",
    "p049": "Generate a photo of a lamp turned on in a dim living room, warm glow.",
    "p050": "Generate a photo of a door slightly ajar with light coming from inside the room.",
    "p051": "Generate a photo of a quiet residential street with parked cars, overcast sky.",
    "p052": "Generate a photo of a city sidewalk with pedestrians in the distance, natural daylight.",
    "p053": "Generate a photo of a bicycle locked to a metal rack on a sidewalk, urban setting.",
    "p054": "Generate a photo of a small neighborhood park with benches and trees, afternoon light.",
    "p055": "Generate a photo of a street corner with traffic lights and crosswalk markings.",
    "p056": "Generate a photo of a building entrance with glass doors reflecting the street.",
    "p057": "Generate a photo of a parking lot with a few cars, cloudy sky.",
    "p058": "Generate a photo of a bus stop sign beside the road, urban background.",
    "p059": "Generate a photo of a street with wet pavement after rain, reflections visible.",
    "p060": "Generate a photo of an alleyway between buildings, muted lighting.",
    "p061": "Generate a photo of a storefront window with items displayed inside.",
    "p062": "Generate a photo of a residential building facade with balconies.",
    "p063": "Generate a photo of a sidewalk café seating area with empty chairs.",
    "p064": "Generate a photo of a pedestrian bridge with railings, overcast weather.",
    "p065": "Generate a photo of a city street at dusk, streetlights beginning to turn on.",
    "p066": "Generate a photo of a small public square with benches and trash cans.",
    "p067": "Generate a photo of a parking garage entrance, concrete structure.",
    "p068": "Generate a photo of a residential driveway with a parked car.",
    "p069": "Generate a photo of a street sign on a pole, clear background.",
    "p070": "Generate a photo of a bike lane painted on the road.",
    "p071": "Generate a photo of a sidewalk covered in fallen leaves, autumn light.",
    "p072": "Generate a photo of a crosswalk at an intersection, daytime lighting.",
    "p073": "Generate a photo of a bus pulling away from a stop, slight motion blur.",
    "p074": "Generate a photo of a city block with mixed residential and commercial buildings.",
    "p075": "Generate a photo of a quiet street at night with illuminated windows.",
    "p076": "Generate a close-up photo of a hand holding a smartphone, natural lighting, realistic skin texture.",
    "p077": "Generate a photo of a smartphone lying on a wooden table, soft indoor lighting.",
    "p078": "Generate a photo of a pair of shoes placed near a doorway.",
    "p079": "Generate a photo of a backpack resting against a wall indoors.",
    "p080": "Generate a photo of a reusable water bottle on a desk.",
    "p081": "Generate a photo of a coffee cup on a table, shallow depth of field.",
    "p082": "Generate a photo of a notebook open on a desk with handwritten notes.",
    "p083": "Generate a photo of a pen and keys on a kitchen counter.",
    "p084": "Generate a photo of a wallet placed next to a phone on a table.",
    "p085": "Generate a photo of a pair of headphones resting on a desk.",
    "p086": "Generate a photo of a pair of glasses folded on a book.",
    "p087": "Generate a photo of a watch lying on a bedside table.",
    "p088": "Generate a photo of a shopping bag on the floor near a chair.",
    "p089": "Generate a photo of a laptop charger plugged into a wall outlet.",
    "p090": "Generate a photo of a chair beside a window with daylight coming in.",
    "p091": "Generate a photo of a plate with leftover food on a table.",
    "p092": "Generate a photo of a set of keys hanging on a hook.",
    "p093": "Generate a photo of a notebook and coffee cup on a café table.",
    "p094": "Generate a photo of a folded jacket placed on a chair.",
    "p095": "Generate a photo of a trash bin near a sidewalk.",
    "p096": "Generate a photo of a grocery receipt on a kitchen counter.",
    "p097": "Generate a photo of a door handle in close-up, indoor lighting.",
    "p098": "Generate a photo of a light switch on a wall.",
    "p099": "Generate a photo of a window view showing nearby buildings.",
    "p100": "Generate a photo of a table with scattered papers and a pen, natural daylight.",
    # p101-p250: Extended prompts
    "p101": "Generate a photorealistic image of a weathered wooden fence in a suburban backyard.",
    "p102": "Generate a photorealistic image of a gravel driveway leading to a detached garage.",
    "p103": "Generate a photorealistic image of an empty playground swing set at dusk.",
    "p104": "Generate a photorealistic image of a puddle on asphalt reflecting streetlights.",
    "p105": "Generate a photorealistic image of a cracked sidewalk with weeds growing through.",
    "p106": "Generate a photorealistic image of a mailbox at the end of a rural dirt road.",
    "p107": "Generate a photorealistic image of a fire hydrant on a city street corner.",
    "p108": "Generate a photorealistic image of an overgrown garden bed in front of a house.",
    "p109": "Generate a photorealistic image of a rusty chain-link fence around a vacant lot.",
    "p110": "Generate a photorealistic image of a pothole filled with rainwater on a road.",
    "p111": "Generate a photorealistic image of a power line pole against a cloudy sky.",
    "p112": "Generate a photorealistic image of a storm drain grate on a wet street.",
    "p113": "Generate a photorealistic image of a faded stop sign at a rural intersection.",
    "p114": "Generate a photorealistic image of a broken streetlight in a parking lot.",
    "p115": "Generate a photorealistic image of a picnic table in a public park.",
    "p116": "Generate a photorealistic image of a trash can overflowing near a bus stop.",
    "p117": "Generate a photorealistic image of a bicycle chained to a street sign pole.",
    "p118": "Generate a photorealistic image of a newspaper vending machine on a sidewalk.",
    "p119": "Generate a photorealistic image of a crosswalk button on a metal pole.",
    "p120": "Generate a photorealistic image of a manhole cover on wet pavement.",
    "p121": "Generate a photorealistic image of a faded parking space line in a lot.",
    "p122": "Generate a photorealistic image of a drainage ditch beside a country road.",
    "p123": "Generate a photorealistic image of a utility box on a residential street.",
    "p124": "Generate a photorealistic image of a wooden telephone pole with flyers stapled.",
    "p125": "Generate a photorealistic image of a metal bench at a train station platform.",
    "p126": "Generate a photorealistic image of a farm barn exterior with peeling red paint.",
    "p127": "Generate a photorealistic image of a harbor with cargo ships and cranes.",
    "p128": "Generate a photorealistic image of a beach lifeguard tower at midday.",
    "p129": "Generate a photorealistic image of a mountain trailhead sign with worn lettering.",
    "p130": "Generate a photorealistic image of a vineyard row at sunset with golden light.",
    "p131": "Generate a photorealistic image of a frozen pond with thin ice and snow edges.",
    "p132": "Generate a photorealistic image of a covered bridge in autumn foliage.",
    "p133": "Generate a photorealistic image of a campsite fire pit with charred logs.",
    "p134": "Generate a photorealistic image of a desert highway stretching to the horizon.",
    "p135": "Generate a photorealistic image of a fishing dock at calm lake in morning mist.",
    "p136": "Generate a photorealistic image of a ski lodge exterior with snowdrifts.",
    "p137": "Generate a photorealistic image of a windmill on flat farmland at dusk.",
    "p138": "Generate a photorealistic image of a rocky coastal tide pool at low tide.",
    "p139": "Generate a photorealistic image of a sunflower field under partly cloudy sky.",
    "p140": "Generate a photorealistic image of a forest floor with fallen leaves and mushrooms.",
    "p141": "Generate a photorealistic image of a city rooftop view with water towers.",
    "p142": "Generate a photorealistic image of an abandoned rail yard with rusted tracks.",
    "p143": "Generate a photorealistic image of a greenhouse interior with potted plants rows.",
    "p144": "Generate a photorealistic image of a ferry terminal waiting area with benches.",
    "p145": "Generate a photorealistic image of a foggy rural cemetery at dawn.",
    "p146": "Generate a photorealistic image of a roadside fruit stand with handwritten signs.",
    "p147": "Generate a photorealistic image of a quiet snow-covered city street at night.",
    "p148": "Generate a photorealistic image of a riverbank picnic table with scattered crumbs.",
    "p149": "Generate a photorealistic image of a small waterfall in a forest clearing.",
    "p150": "Generate a photorealistic image of a dirt bike parked beside a trail.",
    "p151": "Generate a photorealistic image of a classic car parked on a suburban street at sunset.",
    "p152": "Generate a photorealistic image of a fishing pier extending into ocean waves.",
    "p153": "Generate a photorealistic image of a construction worker's hard hat resting on concrete.",
    "p154": "Generate a photorealistic image of a wet cobblestone street reflecting streetlights.",
    "p155": "Generate a photorealistic image of a wind turbine field under cloudy sky.",
    "p156": "Generate a photorealistic image of a rocky mountain summit with expansive valley below.",
    "p157": "Generate a photorealistic image of a bicycle leaning against a brick wall with ivy.",
    "p158": "Generate a photorealistic image of a greenhouse tomato vine close-up.",
    "p159": "Generate a photorealistic image of a car interior dashboard at night.",
    "p160": "Generate a photorealistic image of a snowplow clearing a suburban street.",
    "p161": "Generate a photorealistic image of a small wooden cabin in forest during rainfall.",
    "p162": "Generate a photorealistic image of a lighthouse interior staircase spiral.",
    "p163": "Generate a photorealistic image of a backyard swimming pool with ripples.",
    "p164": "Generate a photorealistic image of a dirt hiking boot resting on rocky terrain.",
    "p165": "Generate a photorealistic image of a rainy bus window with city lights blurred.",
    "p166": "Generate a photorealistic image of a ferris wheel at state fair during twilight.",
    "p167": "Generate a photorealistic image of a beekeeper inspecting honeycomb frames.",
    "p168": "Generate a photorealistic image of a vintage record player with vinyl spinning.",
    "p169": "Generate a photorealistic image of a farmer's hand holding freshly picked radishes.",
    "p170": "Generate a photorealistic image of a bookshelf corner with worn leather books.",
    "p171": "Generate a photorealistic image of a golf course fairway at dawn with dew.",
    "p172": "Generate a photorealistic image of a pottery wheel with wet clay mid-spin.",
    "p173": "Generate a photorealistic image of a mechanic's toolbox inside dusty garage.",
    "p174": "Generate a photorealistic image of a snowy mountain road with guardrail.",
    "p175": "Generate a photorealistic image of a carnival game booth with stuffed prizes.",
    "p176": "Generate a photorealistic image of a potter's kiln with ceramic pieces inside.",
    "p177": "Generate a photorealistic image of a rustic wine barrel stacked in cellar.",
    "p178": "Generate a photorealistic image of a foggy harbor with lobster traps stacked.",
    "p179": "Generate a photorealistic image of a gravel quarry with heavy machinery.",
    "p180": "Generate a photorealistic image of a roadside motel neon sign at dusk.",
    "p181": "Generate a photorealistic image of a train crossing gate lowered on rural road.",
    "p182": "Generate a photorealistic image of a campfire smoke rising into night sky.",
    "p183": "Generate a photorealistic image of a fishing tackle box open on boat deck.",
    "p184": "Generate a photorealistic image of a mailbox at end of snowy gravel driveway.",
    "p185": "Generate a photorealistic image of a swing set in backyard with fallen leaves.",
    "p186": "Generate a photorealistic image of an old cemetery headstone with lichen.",
    "p187": "Generate a photorealistic image of a laundry room with stacked machines.",
    "p188": "Generate a photorealistic image of a stone garden bench under wisteria.",
    "p189": "Generate a photorealistic image of a chef's cutting board with diced vegetables.",
    "p190": "Generate a photorealistic image of a desert cactus garden at midday.",
    "p191": "Generate a photorealistic image of a subway station tiles and turnstile.",
    "p192": "Generate a photorealistic image of a roofer laying shingles on sunny day.",
    "p193": "Generate a photorealistic image of a vintage diner interior with red booths.",
    "p194": "Generate a photorealistic image of a basketball court net close-up at dusk.",
    "p195": "Generate a photorealistic image of an old brick factory chimney against blue sky.",
    "p196": "Generate a photorealistic image of a garden hose coiled on weathered deck.",
    "p197": "Generate a photorealistic image of a ski lift chair ascending mountain slope.",
    "p198": "Generate a photorealistic image of a barber pole on brick storefront.",
    "p199": "Generate a photorealistic image of a car wash tunnel with foam and brushes.",
    "p200": "Generate a photorealistic image of a foggy tennis court early morning.",
    "p201": "Generate a photorealistic image of a city parking garage spiral ramp.",
    "p202": "Generate a photorealistic image of a rain gutter draining water during storm.",
    "p203": "Generate a photorealistic image of a row boat moored in shallow lake.",
    "p204": "Generate a photorealistic image of a hay bale stack in metal barn.",
    "p205": "Generate a photorealistic image of a motorcycle helmet resting on handlebar.",
    "p206": "Generate a photorealistic image of a broken streetlight on empty sidewalk.",
    "p207": "Generate a photorealistic image of a hot tub on patio at night.",
    "p208": "Generate a photorealistic image of a beachside bonfire pit after use.",
    "p209": "Generate a photorealistic image of a museum hallway with arched ceiling.",
    "p210": "Generate a photorealistic image of a mailman walking residential street.",
    "p211": "Generate a photorealistic image of a flower delivery van parked on street.",
    "p212": "Generate a photorealistic image of a fire escape ladder on apartment building.",
    "p213": "Generate a photorealistic image of a junkyard stack of old appliances.",
    "p214": "Generate a photorealistic image of a public restroom hand dryer on tile wall.",
    "p215": "Generate a photorealistic image of a treehouse ladder leading up oak trunk.",
    "p216": "Generate a photorealistic image of a snowy field fence line disappearing into distance.",
    "p217": "Generate a photorealistic image of a weathered picket fence with roses.",
    "p218": "Generate a photorealistic image of a vending machine glowing in dark hallway.",
    "p219": "Generate a photorealistic image of a canoe stored upside down on dock.",
    "p220": "Generate a photorealistic image of a rusty chain-link fence in overgrown lot.",
    "p221": "Generate a photorealistic image of a bowling alley lanes with pins standing.",
    "p222": "Generate a photorealistic image of a veterinarian examining cat on table.",
    "p223": "Generate a photorealistic image of a hospital corridor with fluorescent lights.",
    "p224": "Generate a photorealistic image of a church bell tower against sunset sky.",
    "p225": "Generate a photorealistic image of a bicycle rack outside city library.",
    "p226": "Generate a photorealistic image of a road construction zone with orange cones.",
    "p227": "Generate a photorealistic image of a drive-in movie screen at twilight.",
    "p228": "Generate a photorealistic image of a rooftop pigeon flock near ventilation units.",
    "p229": "Generate a photorealistic image of a garden shed door ajar with tools inside.",
    "p230": "Generate a photorealistic image of a snow-covered mailbox along rural highway.",
    "p231": "Generate a photorealistic image of a hotel lobby chandelier reflecting on marble floor.",
    "p232": "Generate a photorealistic image of a factory conveyor belt with cardboard boxes.",
    "p233": "Generate a photorealistic image of a rocky coastal cliff under cloudy sky.",
    "p234": "Generate a photorealistic image of a paint-splattered artist palette on studio table.",
    "p235": "Generate a photorealistic image of a barn owl perched on fence post at dusk.",
    "p236": "Generate a photorealistic image of a carnival cotton candy cart close-up.",
    "p237": "Generate a photorealistic image of a sewing machine with fabric mid-stitch.",
    "p238": "Generate a photorealistic image of a campsite tarp sheltering gear during rain.",
    "p239": "Generate a photorealistic image of a broken escalator in empty mall.",
    "p240": "Generate a photorealistic image of a newspaper stand on busy city corner.",
    "p241": "Generate a photorealistic image of a library reading room with tall windows.",
    "p242": "Generate a photorealistic image of a horse stable interior with hay on floor.",
    "p243": "Generate a photorealistic image of a fire hydrant on cracked sidewalk corner.",
    "p244": "Generate a photorealistic image of a delivery truck backing into loading dock.",
    "p245": "Generate a photorealistic image of a greenhouse glass roof with condensation.",
    "p246": "Generate a photorealistic image of a fishing boat docked at wooden pier.",
    "p247": "Generate a photorealistic image of a weathered basketball backboard in alley.",
    "p248": "Generate a photorealistic image of a rainy day puddle reflecting building.",
    "p249": "Generate a photorealistic image of a dentist office chair under bright light.",
    "p250": "Generate a photorealistic image of a rocky mountain stream flowing over uneven stones.",
}

# Demo prompts - highly detailed photorealistic prompts for demonstration
DEMO_PROMPTS = {
    "d001": "Create a highly photorealistic candid image of a commuter standing on a rainy train platform at night, captured on a full-frame DSLR with an 85mm f/1.8 lens. Wet pavement reflections, subtle motion blur from passing train lights, realistic skin texture with slight blemishes, damp hair strands sticking together, mixed cool fluorescent and warm sodium lighting, mild chromatic aberration near edges, natural sensor grain in darker areas.",
    "d002": "Create a highly photorealistic macro image of a cracked smartphone screen lying on a wooden desk, shot with a 100mm macro lens. Realistic micro-scratches, dust particles on glass surface, natural light from a nearby window, shallow depth of field falloff, slight lens distortion, authentic reflections and imperfect fingerprint smudges.",
    "d003": "Create a highly photorealistic landscape image of a fog-covered mountain valley at sunrise, captured with a 70-200mm telephoto lens. Atmospheric haze layering, gradual light gradient in sky, realistic tree density variation, subtle shadow detail in valley floor, accurate depth compression and natural color grading.",
    "d004": "Create a highly photorealistic image of a busy commercial kitchen prep station, stainless steel surfaces with visible fingerprints and smudges, steam rising from hot pan, overhead fluorescent lighting casting realistic shadows, minor grease splatter on counter, natural clutter and asymmetry.",
    "d005": "Create a highly photorealistic image of a snow-covered residential street during light snowfall at dusk, shot with a 35mm lens. Falling snowflakes captured at varying motion blur lengths, cold blue ambient tones mixed with warm window lights, tire tracks in fresh snow, realistic atmospheric diffusion.",
    "d006": "Create a highly photorealistic wildlife image of a deer standing near the edge of a forest clearing, captured with a 300mm telephoto lens. Natural fur texture with uneven strands, subtle breath condensation in cool air, realistic depth separation from blurred background foliage, accurate shadow falloff.",
    "d007": "Create a highly photorealistic interior image of a cluttered garage workshop, concrete floor with oil stains, tools hanging slightly uneven on pegboard, single overhead bulb casting harsh directional shadows, realistic dust in air illuminated by light beam, natural color temperature imbalance.",
    "d008": "Create a highly photorealistic image of ocean waves crashing against a rocky cliff during overcast weather, captured with a 70mm lens. Fine sea spray misting the air, motion blur in water while rocks remain sharp, realistic foam texture variation, muted natural color palette.",
    "d009": "Create a highly photorealistic image of a city street viewed through a rain-covered car windshield at night, shallow focus on water droplets, distorted bokeh from streetlights, realistic interior dashboard reflection, natural sensor noise in darker areas.",
    "d010": "Create a highly photorealistic close-up of a ceramic coffee mug with visible chips and minor glaze imperfections, sitting on a textured wooden table in morning light. Subtle steam rising with natural diffusion, realistic wood grain detail, accurate light bounce and shadow softness.",
}


def main():
    # Get the project root (parent of scripts/)
    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent
    
    # Define paths
    datasets_dir = project_root / "datasets"
    manual_gen_dir = datasets_dir / "manual-gen-images"
    prompts_dir = manual_gen_dir / "prompts"
    demoprompts_dir = manual_gen_dir / "demoprompts"
    images_dir = manual_gen_dir / "images"
    
    # Create directories if they don't exist
    prompts_dir.mkdir(parents=True, exist_ok=True)
    demoprompts_dir.mkdir(parents=True, exist_ok=True)
    images_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"Created directory structure at: {manual_gen_dir}")
    
    # Create prompt files (p001-p250)
    created_count = 0
    for prompt_id, prompt_text in PROMPTS.items():
        prompt_file = prompts_dir / f"{prompt_id}.txt"
        prompt_file.write_text(prompt_text, encoding="utf-8")
        created_count += 1
    
    print(f"Created {created_count} prompt files in: {prompts_dir}")
    
    # Create demo prompt files (d001-d010)
    demo_count = 0
    for demo_id, demo_text in DEMO_PROMPTS.items():
        demo_file = demoprompts_dir / f"{demo_id}.txt"
        demo_file.write_text(demo_text, encoding="utf-8")
        demo_count += 1
    
    print(f"Created {demo_count} demo prompt files in: {demoprompts_dir}")
    print("Done!")


if __name__ == "__main__":
    main()
